plugins {
    id 'com.android.application' version '9.3.2' apply false
    id 'com.google.gms.google-services' version '4.5.0' apply false
    id 'io.sentry.android.gradle' version '6.19.0' apply false
}

subprojects {
    afterEvaluate {
        if (plugins.hasPlugin("com.android.library") ||
                plugins.hasPlugin("com.android.application")) {
            android {
                compileSdkVersion 37
                buildToolsVersion "37.0.0"
                ndkVersion "27.3.13750724"

                lint {
                    checkReleaseBuilds false
                    disable 'MissingTranslation', 'ExtraTranslation', 'BlockedPrivateApi'
                }

                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_21
                    targetCompatibility JavaVersion.VERSION_21

                    coreLibraryDesugaringEnabled true
                }

                defaultConfig {
                    minSdkVersion 23
                    targetSdkVersion 36
                }

                buildTypes {
                    play {
                        initWith release
                    }
                }

                buildFeatures.buildConfig = true
            }

            dependencies {
                coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.1.5'
            }
        }
    }
}