plugins {
    id 'com.android.test'
    id 'androidx.baselineprofile'
}

android {
    namespace 'app.nekogram.baselineprofile'
    buildToolsVersion "37.0.0"
    compileSdk {
        version = release(37)
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdk 28
        targetSdk 37

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        //testInstrumentationRunnerArguments["androidx.benchmark.compilation.enabled"] = "false"
    }

    targetProjectPath = ":TMessagesProj_App"

}

// This is the configuration block for the Baseline Profile plugin.
// You can specify to run the generators on a managed devices or connected devices.
baselineProfile {
    useConnectedDevices = true
}

dependencies {
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.5.0'
    implementation 'androidx.test.espresso:espresso-core:3.7.0'
    implementation 'androidx.test.ext:junit:1.3.0'
    implementation 'androidx.test.uiautomator:uiautomator:2.4.0'
}

androidComponents {
    onVariants(selector().all()) { v ->
        def artifactsLoader = v.artifacts.getBuiltArtifactsLoader()
        v.instrumentationRunnerArguments.put(
                "targetAppId",
                v.testedApks.map { artifactsLoader.load(it)?.applicationId }
        )
    }
}