name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: outputs

      - name: Display downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            apk/**/*.apk
            bundle/**/*.aab

      - name: Upload to Telegram
        uses: nekogram/upload-with-mtcute@e196262c35b722c4c8eac79c835ec6dbd109e4b8
        with:
          api-id: ${{ secrets.API_ID }}
          api-hash: ${{ secrets.API_HASH }}
          bot-token: ${{ secrets.RELEASE_BOT_TOKEN }}
          chat-id: ${{ secrets.RELEASE_CHANNEL_ID }}
          files: apk/**/*.apk