name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: outputs

      - name: Display downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            apk/**/*.apk
            bundle/**/*.aab